[package]
name = "bity-ic-storage-canister-c2c"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
storage_canister = { path = "../canister", features = [] }
bity-ic-storage-canister-api = { path = "../api", features = [] }
bity-ic-canister-client = { workspace = true }
ic-cdk = { workspace = true }
candid = { workspace = true }
bity-ic-types = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
